[language-server.typos]
# typos-lsp must be on your PATH, or otherwise change this to an absolute path to typos-lsp
command = "typos-lsp"

# Logging level of the language server. Defaults to error.
# Run with helix -v to output LSP logs to the editor log (:log-open)
environment = {"RUST_LOG" = "error"}

# Custom config. Used together with a config file found in the workspace or its parents,
# taking precedence for settings declared in both. Equivalent to the typos `--config` cli argument.
# config.config = "~/code/typos-lsp/crates/typos-lsp/tests/typos.toml"

# How typos are rendered in the editor, can be one of an Error, Warning, Info or Hint.
# Defaults to Warning.
config.diagnosticSeverity = "Warning"

[[language]]
name = "python"
language-servers = ["pylsp", "typos"]

[language-server.pylsp.config.pylsp]
plugins.ruff.enabled = true
plugins.black.enabled = true
plugins.flake8.maxLineLength = 120
plugins.pycodestyle.maxLineLength = 120
plugins.pylsp_mypy.enabled = true
plugins.pylsp_mypy.live_mode = true

[language.formatter]
command = "black"
args = [
  "-", # strdin
  "--quiet",
  "--line-length=120",
]

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "typos"]
formatter = { command = "rustfmt" , args = ["+nightly"] }

[language-server.rust-analyzer]
config = { checkOnSave = { command = "clippy" }, cargo = { allFeatures = true }}

